### ISSUE TITLE
[Feature Request] Attach a Picture of the Front and Back of the Card

### ISSUE THREAD

**Issue by Aaron-von-Awesome** [brarcher/loyalty-card-locker#359] opened 2020-02-27 20:05 UTC
Firstly, thank you very much for this app.  I have been wanted to have more of a "self hosted" option for managing the loyalty cards, etc. :-)

I would like to request the capability to:

1. Take a picture of the front of a card, and attach that to a newly added (or existing) Card
2. Take a picture of the back of a card, and attach that to a newly added (or existing) Card
3. Include pictures of the front and back of the card in the export
4. Ability to import cards with pictures of the front and back of the card

This would be helpful as a "backup" for my physical cards.  In some cases, I can actually get rid of my physical card if I have a picture (digital) copy.

**Comment by brarcher** [comment] 2020-03-01 23:04
This may be a duplicate of https://github.com/brarcher/loyalty-card-locker/issues/144 and https://github.com/brarcher/loyalty-card-locker/issues/86. If you disagree, feel free to re-open.

**Closed** 2020-03-01 23:04 UTC
Labels: duplicate
