### ISSUE TITLE
backup location

### ISSUE THREAD

**Issue by natrius** [brarcher/loyalty-card-locker#237] opened 2018-04-27 12:48 UTC
Let us choose the backup location. 
**Reason**
I have set up an folder for autobackup with nextcloud, loality card locker saves the backup at the root and i have to manually move it to the folder.

**Comment by brarcher** [comment] 2018-04-27 12:56
This is a duplicate of https://github.com/brarcher/loyalty-card-locker/issues/168. If you disagree, let me know.

**Closed by brarcher** 2018-04-27 12:56 UTC
