### ISSUE TITLE
change location of saved cards

### ISSUE THREAD

**Issue by techwebpd** [brarcher/loyalty-card-locker#61] opened 2016-10-28 13:08 UTC
Please add ability to change location where card information saves, i wanna to save it on external sd or owncloud folder, because i wanna reformat my phone and backup all data

**Comment by brarcher** [comment] 2016-10-31 02:19
Allowing the location to be selectable is a good idea, thanks for the suggestion.

Currently the program will attempt to import/export from/to the [external storage location](https://github.com/brarcher/loyalty-card-locker/blob/master/app/src/main/java/protect/card_locker/ImportExportTask.java#L119) on the phone. Is this location not the external SD card location on your phone? If not, where does it point to? If you are not sure, if you attempt to perform an export and catch the logcat logs it will show the path.

**Comment by logic** [comment] 2016-11-30 21:21
Another use case here is that I'd like to sync the card database with a cloud storage provider (Dropbox is a good example), and that requires imports to happen from an arbitrary location that the storage provider syncs to (in my case, `/storage/emulated/0/Android/data/com/dropbox.android/files/[...]`). I suspect OwnCloud/NextCloud users may have similar needs.

**Comment by betsythefc** [comment] 2016-12-02 19:36
Database syncing would be cool to set all of your loyalty cards on multiple devices. I'm not sure if a SQLLite database is the write way to do this, but if the SQL was changed for a text based database, like YAML or XML, it would be easy to read from.

I think reading the "database" from any location would be great because then anyone can use any sync system they want (OwnCloud/NextCloud/Dropbox/Syncthing/etc)

**Comment by brarcher** [comment] 2016-12-03 17:58
Does the dropbox app have an option to receive sent data, so that one could send a file to the application and it would write it under the sync'ed directory? If so, then just adding an option to send the exported file would meet your need, no?

**Comment by brarcher** [comment] 2017-01-28 17:15
This should be resolved in v0.9. If you try that out and feel it is not what you were hoping for, please re-open.

**Closed by brarcher** 2017-01-28 17:15 UTC

**Comment by monreal** [comment] 2017-07-16 19:56
Using the latest version, the export file ends up on the internal storage instead of the SD card in my case (Moto Z Play, Android 7.0). Is this the expected behavior?

**Comment by brarcher** [comment] 2017-07-17 01:45
@monreal, I do not think so. The code which selects the export location is:
```
    private final File sdcardDir = Environment.getExternalStorageDirectory();
    private final File exportFile = new File(sdcardDir, "LoyaltyCardKeychain.csv");
```
According to the getExternalStorageDirectory() call there can be multiple locations, and this only returns the primary. Further, the primary location could be built-in storage, such as an emulated SD card.

Can you describe the setup of the storage of your phone, and if the OS is emulating an SD card which uses internal storage?

Regardless, if the internal storage is being used for the export, does the Share feature still work so that you can backup the data?

**Comment by monreal** [comment] 2017-07-17 19:13
The export ends in /storage/emulated/0/ which is the internal storage location. The micro SD is mounted as /storage/xxxx-xxxx.

If I share to GMail the .csv file is attached to a mail so I guess sharing works fine.

**Comment by brarcher** [comment] 2017-07-20 02:41
I think then that it is functioning as expected. Based on the discussion, it sounded that sharing exported data and being able to import data from an app satisfied everyone's use cases. If you would like to suggest an improvement, please let me know.
