### ISSUE TITLE
Improve the quiet zone for barcodes

### ISSUE THREAD

**Issue by denilsonsa** [brarcher/loyalty-card-locker#195] opened 2018-02-08 08:03 UTC
What's the quiet zone? It's the blank area around a barcode: <https://www.google.com/search?q=quiet+zone+barcode&tbm=isch>

How large should it be? A quick google search says [“The general sizing rule for a minimal quiet zone (QZ) is 10 times the width of the narrowest bar”](https://barcode-labels.com/why-are-quiet-zones-so-important/) for 1D barcodes, [“This is a region 4X wide […] 4X means width of 4 modules”](https://qrworld.wordpress.com/2011/08/09/the-quiet-zone/) for QR code, [“a white space of 2 times the size of a module”](https://barcode-labels.com/why-are-quiet-zones-so-important/) for Datamatrix…

Does it really matter? I don't know. Some scanners might be better than others. But I noticed that the following 1D barcode (from #194) does not have enough quiet zone:

![1D barcode without quiet zone](https://user-images.githubusercontent.com/121676/35935571-26ca6874-0c41-11e8-87af-6163a1a30eda.png)

Is it a real problem? I don't know.

Did I try to scan it? Not recently.

What to do? I'd suggest keeping this in the backlog, but with low priority for now. If someone else is complaining about unreadable barcodes, then this issue should be tackled.

**Comment by brarcher** [comment] 2018-02-11 03:19
I looked at some barcodes on packages, and I see what you mean. Namely, extra whitespace on the sides of the barcodes.

This should be simple enough to resolve by adding some extra space between the barcode and the end of the screen.

**Comment by brarcher** [comment] 2018-02-11 03:30
I've added a change which would add some quite space before and after the barcode. The amount added was a guess. For some phones it will probably be right, but for large phones it may be wrong. If there are reports where the barcodes cannot be scanned, I may need to figure out how to better calculate the needed quite space.

Thanks for mentioning this. I never considered there might be an issue.

**Comment by lgasp** [comment] 2018-02-16 07:38
The barcode scanner in a shop i use stopped working properly starting from v0.19 , maybe because of lack of quiet zone in new versions.
 I tried to revert to an old version from fdroid but installation failed, don't know why.

**Comment by brarcher** [comment] 2018-02-16 13:25
Thanks for the report. The adding of the quiet space will be in the next release, which will come out when I finish one more piece I'm working on.

As for not being able to downgrade, the database did not change recently so I'm not sure why the downgrade would fail.

**Comment by lgasp** [comment] 2018-02-21 19:39
I installed version 0.21 and the issue is solved, the barcode is read in the same place where it didn't work in version 0.20.

 The quiet is there doing its job!


Thank you

Thab

**Comment by brarcher** [comment] 2018-02-21 20:43
Yay! Thanks for confirming!

If someone finds a barcode which no longer scans, and find that the quite space is insufficient, please re-open.

**Closed by brarcher** 2018-02-21 20:43 UTC
