### ISSUE TITLE
app convert to barcode which is not recognized in supermarket

### ISSUE THREAD

**Issue by nkour** [brarcher/loyalty-card-locker#34] opened 2016-04-22 07:23 UTC
I scanned successfully a barcode  only to be converted to a different system which apparently is not supported by the store that created the first barcode that I scanned

**Comment by brarcher** [comment] 2016-04-22 12:50
Can you provide an image of the original barcode as well as the barcode generated by the application? This way I can reproduce the issue and determine if the issue is in the barcode scanning library or in this application.

**Comment by nkour** [comment] 2016-04-30 10:43
![screenshot_2016-04-30-13-36-12](https://cloud.githubusercontent.com/assets/4855416/14935399/fa42c13c-0ed8-11e6-957a-3e080ae02c95.png)
result is not recognized


original:
![media-20150221](https://cloud.githubusercontent.com/assets/4855416/14935414/8bbc1a5a-0ed9-11e6-8066-69a65ad0d41b.jpg)

**Comment by brarcher** [comment] 2016-05-01 01:34
I find that I am able to capture the barcode from your image of the app and reproduce the barcode which is on your loyalty card. I do not believe that the issue is the app is creating an invalid barcode, or a barcode which is of a different type.

From what I have observed, it seems that certain types of barcode scanner used at some stores are not able to read the barcode image from the phone. Maybe it is that the cellphone screen is shiny and messes with the laser scanner, I do not know. Regardless, I think that the root issue is that certain scanners will not be usable with the app.

If you would like to try an experiment to see if my hypothesis is wrong, next time you are at the store bring up the photo of your loyalty card on your phone and let the barcode scanner detect it. If it is able to detect the picture of the loyalty card but not the barcode generated by the app, then perhaps there is more to investigate. Please let me know your findings, if you are able to give it a try.

**Comment by brarcher** [comment] 2016-05-02 01:50
I tried this experiment at a grocery store. I took a photo of a barcode and attempt to scan the image of the barcode on my phone. Unfortunately, the scanner did not detect the barcode.

I think that the Loyalty Card Locker application has a fundamental limitation, in that not all barcode scanners are able to scan a barcode displayed from a phone. I do not think that there is a way around this. As further evidence, the [Stocard](https://play.google.com/store/apps/details?id=de.stocard.stocard&hl=en) app on the Google Play Store mentions the following:

> Several stores still use outdated scanner technologies (laser or flatbed scanners instead of image scanners). These scanners unfortunately cannot read smartphone displays. In this case simply ask the cashier to type in your loyalty card number manually, to get your discounts.

Closing this issue, as it appears nothing can be done to resolve it on the application's side.

**Closed by brarcher** 2016-05-02 01:50 UTC
